/*
 * @Author: IlleniumDillon 147900130@qq.com
 * @Date: 2022-10-30 13:43:27
 * @LastEditors: IlleniumDillon 147900130@qq.com
 * @LastEditTime: 2022-10-31 20:07:17
 * @FilePath: \CODE\MM32\Sfr\MM32_GPIOReg.h
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
#ifndef _MM32_GPIOREG_H_
#define _MM32_GPIOREG_H_

#include "MM32_RegBase.h"

#include "MM32_GPIORegDef.h"

#define MOUDLE_GPIOA		((MM32_GPIO*)GPIOA_BASE)

#define MOUDLE_GPIOB		((MM32_GPIO*)GPIOB_BASE)

#define MOUDLE_GPIOC		((MM32_GPIO*)GPIOC_BASE)

#define MOUDLE_GPIOD		((MM32_GPIO*)GPIOD_BASE)

#define MOUDLE_GPIOE		((MM32_GPIO*)GPIOE_BASE)

#define MOUDLE_GPIOF		((MM32_GPIO*)GPIOF_BASE)

#define MOUDLE_GPIOG		((MM32_GPIO*)GPIOG_BASE)

#define MOUDLE_GPIOH		((MM32_GPIO*)GPIOH_BASE)

#define GPIOA_CRL		((MM32_GPIO_CRL*)(GPIOA_BASE+0X00))

#define GPIOA_CRH		((MM32_GPIO_CRH*)(GPIOA_BASE+0X04))

#define GPIOA_IDR		((MM32_GPIO_IDR*)(GPIOA_BASE+0X08))

#define GPIOA_ODR		((MM32_GPIO_ODR*)(GPIOA_BASE+0X0C))

#define GPIOA_BSRR		((MM32_GPIO_BSRR*)(GPIOA_BASE+0X10))

#define GPIOA_BRR		((MM32_GPIO_BRR*)(GPIOA_BASE+0X14))

#define GPIOA_LCKR		((MM32_GPIO_LCKR*)(GPIOA_BASE+0X18))

#define GPIOA_DCR		((MM32_GPIO_DCR*)(GPIOA_BASE+0X1C))

#define GPIOA_AFRL		((MM32_GPIO_AFRL*)(GPIOA_BASE+0X20))

#define GPIOA_AFRH		((MM32_GPIO_AFRH*)(GPIOA_BASE+0X24))

#define GPIOB_CRL		((MM32_GPIO_CRL*)(GPIOB_BASE+0X00))

#define GPIOB_CRH		((MM32_GPIO_CRH*)(GPIOB_BASE+0X04))

#define GPIOB_IDR		((MM32_GPIO_IDR*)(GPIOB_BASE+0X08))

#define GPIOB_ODR		((MM32_GPIO_ODR*)(GPIOB_BASE+0X0C))

#define GPIOB_BSRR		((MM32_GPIO_BSRR*)(GPIOB_BASE+0X10))

#define GPIOB_BRR		((MM32_GPIO_BRR*)(GPIOB_BASE+0X14))

#define GPIOB_LCKR		((MM32_GPIO_LCKR*)(GPIOB_BASE+0X18))

#define GPIOB_DCR		((MM32_GPIO_DCR*)(GPIOB_BASE+0X1C))

#define GPIOB_AFRL		((MM32_GPIO_AFRL*)(GPIOB_BASE+0X20))

#define GPIOB_AFRH		((MM32_GPIO_AFRH*)(GPIOB_BASE+0X24))

#define GPIOC_CRL		((MM32_GPIO_CRL*)(GPIOC_BASE+0X00))

#define GPIOC_CRH		((MM32_GPIO_CRH*)(GPIOC_BASE+0X04))

#define GPIOC_IDR		((MM32_GPIO_IDR*)(GPIOC_BASE+0X08))

#define GPIOC_ODR		((MM32_GPIO_ODR*)(GPIOC_BASE+0X0C))

#define GPIOC_BSRR		((MM32_GPIO_BSRR*)(GPIOC_BASE+0X10))

#define GPIOC_BRR		((MM32_GPIO_BRR*)(GPIOC_BASE+0X14))

#define GPIOC_LCKR		((MM32_GPIO_LCKR*)(GPIOC_BASE+0X18))

#define GPIOC_DCR		((MM32_GPIO_DCR*)(GPIOC_BASE+0X1C))

#define GPIOC_AFRL		((MM32_GPIO_AFRL*)(GPIOC_BASE+0X20))

#define GPIOC_AFRH		((MM32_GPIO_AFRH*)(GPIOC_BASE+0X24))

#define GPIOD_CRL		((MM32_GPIO_CRL*)(GPIOD_BASE+0X00))

#define GPIOD_CRH		((MM32_GPIO_CRH*)(GPIOD_BASE+0X04))

#define GPIOD_IDR		((MM32_GPIO_IDR*)(GPIOD_BASE+0X08))

#define GPIOD_ODR		((MM32_GPIO_ODR*)(GPIOD_BASE+0X0C))

#define GPIOD_BSRR		((MM32_GPIO_BSRR*)(GPIOD_BASE+0X10))

#define GPIOD_BRR		((MM32_GPIO_BRR*)(GPIOD_BASE+0X14))

#define GPIOD_LCKR		((MM32_GPIO_LCKR*)(GPIOD_BASE+0X18))

#define GPIOD_DCR		((MM32_GPIO_DCR*)(GPIOD_BASE+0X1C))

#define GPIOD_AFRL		((MM32_GPIO_AFRL*)(GPIOD_BASE+0X20))

#define GPIOD_AFRH		((MM32_GPIO_AFRH*)(GPIOD_BASE+0X24))

#define GPIOE_CRL		((MM32_GPIO_CRL*)(GPIOE_BASE+0X00))

#define GPIOE_CRH		((MM32_GPIO_CRH*)(GPIOE_BASE+0X04))

#define GPIOE_IDR		((MM32_GPIO_IDR*)(GPIOE_BASE+0X08))

#define GPIOE_ODR		((MM32_GPIO_ODR*)(GPIOE_BASE+0X0C))

#define GPIOE_BSRR		((MM32_GPIO_BSRR*)(GPIOE_BASE+0X10))

#define GPIOE_BRR		((MM32_GPIO_BRR*)(GPIOE_BASE+0X14))

#define GPIOE_LCKR		((MM32_GPIO_LCKR*)(GPIOE_BASE+0X18))

#define GPIOE_DCR		((MM32_GPIO_DCR*)(GPIOE_BASE+0X1C))

#define GPIOE_AFRL		((MM32_GPIO_AFRL*)(GPIOE_BASE+0X20))

#define GPIOE_AFRH		((MM32_GPIO_AFRH*)(GPIOE_BASE+0X24))

#define GPIOF_CRL		((MM32_GPIO_CRL*)(GPIOF_BASE+0X00))

#define GPIOF_CRH		((MM32_GPIO_CRH*)(GPIOF_BASE+0X04))

#define GPIOF_IDR		((MM32_GPIO_IDR*)(GPIOF_BASE+0X08))

#define GPIOF_ODR		((MM32_GPIO_ODR*)(GPIOF_BASE+0X0C))

#define GPIOF_BSRR		((MM32_GPIO_BSRR*)(GPIOF_BASE+0X10))

#define GPIOF_BRR		((MM32_GPIO_BRR*)(GPIOF_BASE+0X14))

#define GPIOF_LCKR		((MM32_GPIO_LCKR*)(GPIOF_BASE+0X18))

#define GPIOF_DCR		((MM32_GPIO_DCR*)(GPIOF_BASE+0X1C))

#define GPIOF_AFRL		((MM32_GPIO_AFRL*)(GPIOF_BASE+0X20))

#define GPIOF_AFRH		((MM32_GPIO_AFRH*)(GPIOF_BASE+0X24))

#define GPIOG_CRL		((MM32_GPIO_CRL*)(GPIOG_BASE+0X00))

#define GPIOG_CRH		((MM32_GPIO_CRH*)(GPIOG_BASE+0X04))

#define GPIOG_IDR		((MM32_GPIO_IDR*)(GPIOG_BASE+0X08))

#define GPIOG_ODR		((MM32_GPIO_ODR*)(GPIOG_BASE+0X0C))

#define GPIOG_BSRR		((MM32_GPIO_BSRR*)(GPIOG_BASE+0X10))

#define GPIOG_BRR		((MM32_GPIO_BRR*)(GPIOG_BASE+0X14))

#define GPIOG_LCKR		((MM32_GPIO_LCKR*)(GPIOG_BASE+0X18))

#define GPIOG_DCR		((MM32_GPIO_DCR*)(GPIOG_BASE+0X1C))

#define GPIOG_AFRL		((MM32_GPIO_AFRL*)(GPIOG_BASE+0X20))

#define GPIOG_AFRH		((MM32_GPIO_AFRH*)(GPIOG_BASE+0X24))

#define GPIOH_CRL		((MM32_GPIO_CRL*)(GPIOH_BASE+0X00))

#define GPIOH_CRH		((MM32_GPIO_CRH*)(GPIOH_BASE+0X04))

#define GPIOH_IDR		((MM32_GPIO_IDR*)(GPIOH_BASE+0X08))

#define GPIOH_ODR		((MM32_GPIO_ODR*)(GPIOH_BASE+0X0C))

#define GPIOH_BSRR		((MM32_GPIO_BSRR*)(GPIOH_BASE+0X10))

#define GPIOH_BRR		((MM32_GPIO_BRR*)(GPIOH_BASE+0X14))

#define GPIOH_LCKR		((MM32_GPIO_LCKR*)(GPIOH_BASE+0X18))

#define GPIOH_DCR		((MM32_GPIO_DCR*)(GPIOH_BASE+0X1C))

#define GPIOH_AFRL		((MM32_GPIO_AFRL*)(GPIOH_BASE+0X20))

#define GPIOH_AFRH		((MM32_GPIO_AFRH*)(GPIOH_BASE+0X24))

#endif